<main>
	<section id="profile">
		<img id="profile-picture" title="Mathieu Lichtsteiner" alt="Das Profilbild von Mathieu Lichtsteiner, dem Designer." src="img/profile.jpg" />
		<h1>Mathieu's MakeUp-Studio</h1>
		<h3>von Mathieu Lichtsteiner</h3>
		<!-- Sollte ein relativer URL sein, da es sich aber in der Landing-Section (unbewertet) befindet ist es okay.-->
		<h4>
			<a title="Github-Repository mit Github-Pages öffnen" href="https://github.com/Mathieu-Lichtsteiner/WEBT_FS21_Projekt" target="_blank" rel="noreferrer noopener">Github-Repository</a>
		</h4>
	</section>

	<section id="information">
		<h2>Informationen</h2>
		<p style="text-align: center">
			Willkommen auf meiner Webseite!<br />
			Diese habe ich als Abschlussprojekt im Modul
			<em>Webtechnologien</em> gestaltet und eingereicht. Es geht darum eigene
			Bilder hochzuladen und diese mit einem lustigen MakeUp zu versehen.
			Schlussendlich kann unter <a href="#submit">"Beitrag posten"</a> die
			Kreation hochgeladen werden und unter
			<a href="#posts">"Bisherige Beiträge ansehen"</a> bestaunt werden.
			<br />
			<strong>Viel Spass!</strong>
		</p>
		<table id="informationTable">
			<tr>
				<td class="symbol">
					<img alt="Symbol für upload" src="img/upload.svg" width="32" height="32" />
				</td>
				<td>
					<h4>Bild hochladen</h4>
					<p>
						Hier können Sie ein Bild auswählen, dass Sie bemalen möchten.
						<strong>Achtung,</strong> dabei wird Ihr bisheriges "MakeUp"
						zurückgesetzt!
					</p>
				</td>
			</tr>
			<tr>
				<td class="symbol">&#10060;</td>
				<td>
					<h4>Bild zurücksetzen</h4>
					<p>
						Hier können Sie das Hintergrundbild löschen und auf einer weissen
						Leinwand malen. Falls Sie Ihr Bild wieder möchten, benutzen Sie den
						nächsten Knopf <em>"MakeUp zurücksetzen".</em>
					</p>
				</td>
			</tr>
			<tr>
				<td class="symbol">
					<img alt="Symbol für löschen" src="img/clear.svg" width="32" height="32" />
				</td>
				<td>
					<h4>MakeUp zurücksetzen</h4>
					<p>
						Hierbei wird Ihr makeUp gelöscht und auf das hochgeladene Bild
						zurückgesetzt.
					</p>
				</td>
			</tr>
			<tr>
				<td class="symbol">&#128393;</td>
				<td>
					<h4>Freihand zeichnen</h4>
					<p>
						Einfaches zeichnen, wie Sie es mit Farbstiften tun würden, aber halt
						mit der maus. Funktioniert ähnlich wie "Drag & Drop" also drücken &
						halten um zu zeichnen!
					</p>
				</td>
			</tr>
			<tr>
				<td class="symbol">&#9585;</td>
				<td>
					<h4>Linie / Pfad zeichnen</h4>
					<p>
						Mit diesem Tool können Sie Linien zeichnen. Dabei wird ein Linienzug
						erstellt, bis Sie einen Doppelklick machen. Dann beginnt ein neuer
						Pfad.
					</p>
				</td>
			</tr>
			<tr>
				<td class="symbol">&#9711;</td>
				<td>
					<h4>Kreis zeichnen</h4>
					<p>
						Mit drei Klicks können Sie bestimmen, wo ein Kreis platziert werden
						soll. Achtung, braucht etwas übung, um es perfekt zu machen.
					</p>
				</td>
			</tr>
			<tr>
				<td class="symbol">&#8276;</td>
				<td>
					<h4>Bogen zeichnen</h4>
					<p>
						Mit drei Klicks können Sie bestimmen, wo ein Bogen platziert werden
						soll. Dabei können nur Kreisförmige und keine elliptischen Segmente
						platziert werden.
					</p>
				</td>
			</tr>
			<tr>
				<td class="symbol">&rect;</td>
				<td>
					<h4>Rechteck zeichnen</h4>
					<p>
						Mittels zwei Klicks können sie die Eckpunkte eines Rechtecks
						bestimmen, bzw. zeichnen.
					</p>
				</td>
			</tr>
			<tr>
				<td class="symbol">&#9651;</td>
				<td>
					<h4>Dreieck zeichnen</h4>
					<p>Mit drei Klicks können Sie ein Dreieck zeichnen.</p>
				</td>
			</tr>
			<tr>
				<td class="symbol">
					<div id="colorExample"></div>
				</td>
				<td>
					<h4>Farbe auswählen</h4>
					<p>
						Mit diesem unbeschrifteten Rechteck können Sie die zeichen-Farbe
						definieren.
					</p>
				</td>
			</tr>
		</table>
	</section>
</main>