<section id="home">
	<img id="profile-picture" title="Mathieu Lichtsteiner" alt="Das Profilbild von Mathieu Lichtsteiner, dem Designer." src="img/profile.jpg" />
	<h1>Mathieu's MakeUp-Studio</h1>
	<h3>von Mathieu Lichtsteiner</h3>
	<!-- Sollte ein relativer URL sein, da es sich aber in der Landing-Section (unbewertet) befindet ist es okay.-->
	<h4>
		<a id="test" title="Github-Repository mit Github-Pages öffnen" href="https://github.com/Mathieu-Lichtsteiner/WEBT_FS21_Projekt" target="_blank" rel="noreferrer noopener">Github-Repository</a>
	</h4>
</section>

<section id="information">
	<h2>Informationen</h2>
	<p style="text-align: center;">Willkommen auf meiner Webseite!<br /> Diese habe ich als Abschlussprojekt im
		Modul <em>Webtechnologien</em>
		gestaltet und eingereicht. Es geht darum eigene Bilder hochzuladen und diese mit einem lustigen MakeUp zu
		versehen. Schlussendlich kann unter <a href="#submit">"Beitrag posten"</a> die Kreation hochgeladen werden
		und unter <a href="#posts">"Bisherige Beiträge ansehen"</a> bestaunt werden.
		<br />
		<strong>Viel Spass!</strong>
	</p>
	<table id="informationTable">
		<tr>
			<td class="symbol"><img alt="Symbol für upload" src="img/upload.svg" width="32" height="32" /></td>
			<td>
				<h4>Bild hochladen</h4>
				<p>Hier können Sie ein Bild auswählen, dass Sie bemalen möchten. <strong>Achtung,</strong> dabei
					wird Ihr bisheriges "MakeUp" zurückgesetzt!</p>
			</td>
		</tr>
		<tr>
			<td class="symbol">&#10060;</td>
			<td>
				<h4>Bild zurücksetzen</h4>
				<p>Hier können Sie das Hintergrundbild löschen und auf einer weissen Leinwand malen. Falls Sie Ihr
					Bild wieder möchten, benutzen Sie den nächsten Knopf <em>"MakeUp zurücksetzen".</em></p>
			</td>
		</tr>
		<tr>
			<td class="symbol"><img alt="Symbol für löschen" src="img/clear.svg" width="32" height="32"></td>
			<td>
				<h4>MakeUp zurücksetzen</h4>
				<p>Hierbei wird Ihr makeUp gelöscht und auf das hochgeladene Bild zurückgesetzt.</p>
			</td>
		</tr>
		<tr>
			<td class="symbol">&#128393;</td>
			<td>
				<h4>Freihand zeichnen</h4>
				<p>Einfaches zeichnen, wie Sie es mit Farbstiften tun würden, aber halt mit der maus. Funktioniert
					ähnlich wie "Drag & Drop" also drücken & halten um zu zeichnen!</p>
			</td>
		</tr>
		<tr>
			<td class="symbol">&#9585;</td>
			<td>
				<h4>Linie / Pfad zeichnen</h4>
				<p>Mit diesem Tool können Sie Linien zeichnen. Dabei wird ein Linienzug erstellt, bis Sie einen
					Doppelklick machen. Dann beginnt ein neuer Pfad.</p>
			</td>
		</tr>
		<tr>
			<td class="symbol">&#9711;</td>
			<td>
				<h4>Kreis zeichnen</h4>
				<p>Mit drei Klicks können Sie bestimmen, wo ein Kreis platziert werden soll. Achtung, braucht etwas
					übung, um es perfekt zu machen.</p>
			</td>
		</tr>
		<tr>
			<td class="symbol">&#8276;</td>
			<td>
				<h4>Bogen zeichnen</h4>
				<p>Mit drei Klicks können Sie bestimmen, wo ein Bogen platziert werden soll. Dabei können nur
					Kreisförmige und keine elliptischen Segmente platziert werden. </p>
			</td>
		</tr>
		<tr>
			<td class="symbol">&rect;</td>
			<td>
				<h4>Rechteck zeichnen</h4>
				<p>Mittels zwei Klicks können sie die Eckpunkte eines Rechtecks bestimmen, bzw. zeichnen.</p>
			</td>
		</tr>
		<tr>
			<td class="symbol">&#9651;</td>
			<td>
				<h4>Dreieck zeichnen</h4>
				<p>Mit drei Klicks können Sie ein Dreieck zeichnen. </p>
			</td>
		</tr>
		<tr>
			<td class="symbol">
				<div id="colorExample"></div>
			</td>
			<td>
				<h4>Farbe auswählen</h4>
				<p>Mit diesem unbeschrifteten Rechteck können Sie die zeichen-Farbe definieren.</p>
			</td>
		</tr>
	</table>
</section>

<section id="draw">
	<h2>MakeUp designen</h2>
	<div id="canvasSection">
		<div id="canvasContainer">
			<canvas id="canvas" width="940" height="600">
				<p>Wenn Sie das sehen, unterstützt Ihr Browser leider kein HTML5 und das benötigte Canvas-Element
					nicht.</p>
			</canvas>
		</div>
		<div id="controlColumn">
			<form action="php/submitUpload.php" method="POST" enctype="multipart/form-data" id="fileContainer" class="w3-button control symbol">
				<label title="Bild hochladen">
					<!-- Icon von https://materialdesignicons.com/ "tray-arrow-up" gespeichert als upload.svg -->
					<img alt="Symbol für upload" src="img/upload.svg" width="32" height="32" />
					<!-- Der input ist versteckt, aber das Label delegiert den Click direkt weiter (idee hier aufgenommen: https://stackoverflow.com/questions/21842274/cross-browser-custom-styling-for-file-upload-button)-->
					<input id="fileInput" name="fileInput" type="file" accept=".jpg,.jpeg,.png" onchange="this.form.submit();" />
				</label>
			</form>
			<button title="Bild zurücksetzen" onclick="clearCanvas();" name="clearImage" class="w3-button control symbol">
				&#10060;
			</button>
			<!-- Icon von https://materialdesignicons.com/ "autorenew" gespeichert als clear.svg -->
			<button title="MakeUp zurücksetzen" onclick="clearMakeUp();" name="clearDrawing" class="w3-button control symbol">
				<img alt="Symbol für löschen" src="img/clear.svg" width="32" height="32">
			</button>
			<button title="Freihand zeichnen" onclick="setMode(this.name);" name="freehand" class="w3-button control symbol">
				&#128393;
			</button>
			<button title="Linie zeichnen" onclick="setMode(this.name);" name="line" class="w3-button control symbol">
				&#9585;
			</button>
			<button title="Kreis zeichnen" onclick="setMode(this.name);" name="circle" class="w3-button control symbol">
				&#9711;
			</button>
			<button title="Bogen zeichnen" onclick="setMode(this.name);" name="arc" class="w3-button control symbol">
				&#8276;
			</button>
			<button title="Rechteck zeichnen" onclick="setMode(this.name);" name="rectangle" class="w3-button control symbol">
				&rect;
			</button>
			<button title="Dreieck zeichnen" onclick="setMode(this.name);" name="triangle" class="w3-button control symbol">
				&#9651;
			</button>
			<input title="Farbe wählen" onchange="setColor(this.value);" type="color" id="colorPicker" class="w3-button control symbol" />
		</div>
	</div>
</section>

<section id="submit">
	<!-- Ich habe hier keine labels mit dem "for" Attribut genutzt, da mir das Design mit den Placeholder Attributen deutlich besser gefällt. mit dem "alt" Attribut wird Screenreadern auch genügend information geliefert.-->
	<h2>Beitrag posten</h2>
	<form name="submitForm" action="php/submitPost.php" method="POST" onsubmit="appendCanvasToForm(); return validateForm();">
		<div class="w3-col m6">
			<div class="w3-col l6">
				<label for="firstName" class="w3-label">Vorname: </label>
				<input id="firstName" name="firstName" type="text" placeholder="Angelica" class="w3-input" required minlength="2" maxlength="30" />
			</div>
			<div class="w3-col l6">
				<label for="lastName" class="w3-label">Nachname: </label>
				<input id="lastName" name="lastName" type="text" placeholder="Mustermann" class="w3-input" required minlength="2" maxlength="30" />
			</div>
			<div class="w3-col">
				<label for="email" class="w3-label">Email: </label>
				<!-- Patternmatching mit RegEx: muss ein x@y.z enthalten, wobei x,y,z buchstaben & zahlen sein können. y&z müssen 2 oder länger sein -->
				<input id="email" name="email" type="email" placeholder="ihre.email@provider.ch" class="w3-input" required maxlength="100" pattern="(.+)(@)(.{2,})(\.)(.{2,})" />
			</div>
		</div>
		<div class="w3-col m6">
			<label for="message" class="w3-label">Nachricht: </label>
			<textarea id="message" name="message" placeholder="Inspiriert von Lady Gaga!" class="w3-input" rows="4"></textarea>
		</div>
		<input type="submit" id="submitButton" class="w3-input">
		<!-- Hidden input-Felder für zusätzliche Daten: https://stackoverflow.com/questions/8021748/how-to-add-additional-parameters-on-a-form-submitting-it-with-get-method -->
		<input type="hidden" id="submitCanvas" name="submitCanvas" />
		<input type="hidden" id="deleteImage" name="deleteImage" />
	</form>
</section>

<section id="posts">
	<h2>Bisherige Beiträge ansehen.</h2>
	<button id="loadMore" class="w3-input" onclick="loadPosts();">Mehr Posts laden!</button>
	<!-- Erste beiträge laden aktualisieren -->
	<script>
		loadPosts(true);
	</script>
</section>