<!DOCTYPE html>
<html lang="de">

<head>
	<meta charset="UTF-8" />
	<meta name="author" content="Mathieu Lichtsteiner" />
	<meta name="description" content="Das ist das Resultat des Unterrichts im Modul &quot;Webtechnologien&quot;. Diese Webseite ist mit Humor zu geniessen..." />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>
		Mathieu's MakeUp Studio
	</title>

	<script type="module">
		import toggleNav from "./js/nav/toggleNav.mjs";
		// Add the Events for the Nav-Menu
		for (const button of document.getElementsByName("navButton")) {
			button.addEventListener("click", () => {
				toggleNav(true);
			});
		}
		document.getElementById("hamburger").addEventListener("click", () => {
			toggleNav();
		});
	</script>

	<!-- Trick gelernt von: https://css-tricks.com/emojis-as-favicons/ dabei habe Ich den Code des Inline-SVGs gespeichert und nutze hier nur den link auf die Datei. -->
	<!-- &#128132; from https://www.utf8icons.com/character/128132/lipstick -->
	<link rel="shortcut icon" href="img/lipstick.svg">
	<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css" />
	<link rel="stylesheet" href="css/main.css" />
	<link rel="stylesheet" href="css/responsiveCanvas.css" />
</head>

<body>

	<nav class="w3-bar w3-white">
		<a id="hamburger" class="w3-bar-item w3-button w3-mobile w3-hide-medium w3-hide-large">&equiv;</a>
		<a name="navButton" href="?page=home" class="w3-bar-item w3-button w3-mobile w3-hide-small">Home</a>
		<a name="navButton" href="?page=home#information" class="w3-bar-item w3-button w3-mobile w3-hide-small">Informationen</a>
		<a name="navButton" href="?page=draw" class="w3-bar-item w3-button w3-mobile w3-hide-small">Zeichnen und Beitragen!</a>
		<a name="navButton" href="?page=posts" class="w3-bar-item w3-button w3-mobile w3-hide-small">Posts ansehen!</a>
	</nav>

	<div title="nav-Abstand"></div>

	<div title="content-Container">

		<?php require $content; ?>

	</div>

	<div title="footer-Abstand"></div>

</body>

</html>